//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking.App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banking_PayService
    {
        public int Id { get; set; }
        public int ServiceId { get; set; }
        public int UserId { get; set; }
        public int BankAccountId { get; set; }
        public decimal Amount { get; set; }
        public bool Paid { get; set; }
        public System.DateTime PaidDate { get; set; }
    
        public virtual Banking_BankAccount Banking_BankAccount { get; set; }
        public virtual Banking_Service Banking_Service { get; set; }
        public virtual Banking_User Banking_User { get; set; }
    }
}
