//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking.App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banking_Transfer
    {
        public int Id { get; set; }
        public int OriginAccount { get; set; }
        public int DestinationAccount { get; set; }
        public int UserId { get; set; }
        public decimal Balance { get; set; }
        public string Description { get; set; }
        public System.DateTime TransferDate { get; set; }
    
        public virtual Banking_BankAccount Banking_BankAccount { get; set; }
        public virtual Banking_BankAccount Banking_BankAccount1 { get; set; }
        public virtual Banking_User Banking_User { get; set; }
    }
}
